name: cdd_workshop
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip
  - numpy
  - pandas
  - scikit-learn
  - rdkit
  - matplotlib
  - seaborn
  - cpuonly
  - pytorch
  - ipykernel
  - pip:
      - notebook
      - tqdm
