name: cdd_workshop
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - anyio=2.1.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.3.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.4
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.7.0
  - importlib_metadata=3.7.0
  - ipykernel=5.5.0
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.0.1
  - libffi=3.3
  - libgfortran5=9.3.0
  - libglib=2.66.7
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - llvm-openmp=11.0.1
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.3.0
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.2.0
  - numpy=1.20.1
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.2
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - parso=0.8.1
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0.1
  - pixman=0.40.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - ptyprocess=0.7.0
  - pycairo=1.20.0
  - pycparser=2.20
  - pygments=2.8.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.2
  - python-dateutil=2.8.1
  - python-fastjsonschema=2.16.2
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=22.0.3
  - rdkit=2020.09.4
  - readline=8.0
  - reportlab=3.5.60
  - requests=2.25.1
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlalchemy=1.3.23
  - sqlite=3.34.0
  - statsmodels=0.12.2
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - torch==1.13.1
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - appnope==0.1.2

